### ISSUE TITLE
Continued development

### ISSUE THREAD

**Issue by henrik242** [lukhnos/nnio#1]
Is this project still under development?

**Comment by lukhnos** [comment]
I still plan to add some more classes. This being said, it's a personal project, so I can't make any promises. :)

**Comment by henrik242** [comment]
Cool.  I've been looking at adding stuff myself, notably TempFileHelper and Files.

**Comment by lukhnos** [comment]
I've just released [0.2](https://github.com/lukhnos/nnio/tree/0.2) to Maven Central and updated [README](https://github.com/lukhnos/nnio/blob/master/README.md) in master. [`Files`](https://github.com/lukhnos/nnio/blob/master/src/main/java/org/lukhnos/nnio/file/Files.java) is now there, along with a few more classes. Happy new year!

**Comment by kb-1000** [comment]
@lukhnos what's about `File.toPath()`?

**Comment by lukhnos** [comment]
Since `File` is a built-in class it's out of this project's reach. What I did with a project that had quite a lot of `File.toPath()` invocations was to create a utility class (say `MyFileUtils.toPath(File)`) than substitute every `someFile.toPath()` call with `MyFileUtils.toPath(someFile)`.
